### ISSUE TITLE
User can enter the name of a location and then get the attractions around it

### ISSUE THREAD

**Issue by louis-zhangxa** [louis-zhangxa/Aloha#1]
## ⚙️ Feature

User can enter the name of a location and then get the attractions around it

## 📐 Functionality

user can enter a location then submit, them they will get a list of attractions around it

## 🖼️ Wireframes
![Screen Shot 2023-01-09 at 5 01 31 PM](https://user-images.githubusercontent.com/114542582/211438322-04dff30d-e18a-4070-9622-e9423afb154e.png)
![Screen Shot 2023-01-09 at 5 01 52 PM](https://user-images.githubusercontent.com/114542582/211438352-f1765d94-5d03-4d60-90eb-26d7c6d4bccf.png)
![Screen Shot 2023-01-09 at 5 02 29 PM](https://user-images.githubusercontent.com/114542582/211438440-2096611a-8cbf-4f2f-b4ea-a392e94d6f4b.png)
![Screen Shot 2023-01-09 at 5 02 38 PM](https://user-images.githubusercontent.com/114542582/211438447-5ee74045-c8d1-45cd-9313-058202285b94.png)

## ✅ Task List

- [x] add a header with the name of the app
- [x] add a background for the webpage
- [x] add a home page for the website
- [x] add an attractions list for the website
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [x] make it functional
- [x]  Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors
